baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[security]
  enableInlineShortcodes = true
  [security.exec]
    allow = [ "^asciidoctor$" ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

